### tensor.permute(dims)   
- dims：一个包含整数的新维度顺序的元组

In [4]:
import torch

# 创建一个三维张量
tensor = torch.randn(2, 3, 4)

# 使用permute重新排列张量的维度
# 将维度顺序从[2, 3, 4]更改为[3, 2, 4]
tensor_permuted = tensor.permute(1, 0, 2)

# 打印原始张量和重新排列维度后的张量的形状和内容
print("原始张量形状:", tensor.shape)
print(tensor)
print("重新排列维度后的张量形状:", tensor_permuted.shape)
print(tensor_permuted)


原始张量形状: torch.Size([2, 3, 4])
tensor([[[ 0.7673, -0.6361, -1.6773, -0.2347],
         [ 1.4445,  0.4438,  1.3673, -0.4134],
         [ 1.1638, -0.3606,  0.5471, -0.2983]],

        [[ 0.5462,  1.2433, -1.5241, -0.5956],
         [ 0.9521,  0.1408, -1.0522,  0.0779],
         [-0.1250,  1.4738, -0.7332,  0.2156]]])
重新排列维度后的张量形状: torch.Size([3, 2, 4])
tensor([[[ 0.7673, -0.6361, -1.6773, -0.2347],
         [ 0.5462,  1.2433, -1.5241, -0.5956]],

        [[ 1.4445,  0.4438,  1.3673, -0.4134],
         [ 0.9521,  0.1408, -1.0522,  0.0779]],

        [[ 1.1638, -0.3606,  0.5471, -0.2983],
         [-0.1250,  1.4738, -0.7332,  0.2156]]])


 ### tensor.unsqueeze(dim)  
 - dim：指定要添加新维度的位置。这个参数是一个整数，可以是负数，表示从张量的末尾开始计数。

In [2]:
import torch

# 创建一个一维张量
tensor = torch.tensor([1, 2, 3, 4, 5])

# 在第0维（最外层）添加一个新的维度
tensor_unsqueezed = tensor.unsqueeze(0)

# 输出原始张量和增加维度后的张量的形状
print("原始张量形状:", tensor.shape)
print("增加维度后的张量形状:", tensor_unsqueezed.shape)


原始张量形状: torch.Size([5])
增加维度后的张量形状: torch.Size([1, 5])


### torch.repeat(*sizes) → Tensor
- sizes: 一个包含整数序列的元组，指定在每个维度上张量需要重复的次数。

In [ ]:
import torch

# 创建一个形状为 [2, 3] 的张量
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 使用 repeat 函数
y = x.repeat(2, 3)

print(y)
#在这个例子中，原始张量 x 的形状是 [2, 3]。通过调用 repeat(2, 3)，我们告诉PyTorch在第一个维度（行）上重复2次，在第二个维度（列）上重复3次。因此，最终得到的张量 y 的形状是 [4, 9]。




tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]])


In [12]:
import torch
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 在新的维度上重复
z = x.unsqueeze(0).repeat(2, 1, 1)
print(z)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


### tensor.masked_fill_(mask, value)  
- mask：一个与tensor形状相同的布尔型张量，用于指定要填充的元素位置。
- value：要填充的值。

In [3]:
import torch

# 创建一个张量
tensor = torch.tensor([1, 2, 3, 4, 5])

# 创建一个掩码，指定要填充的元素位置
mask = torch.tensor([False, True, False, True, False])

# 使用masked_fill_填充张量
tensor.masked_fill_(mask, -1)

# 输出填充后的张量
print(tensor)


tensor([ 1, -1,  3, -1,  5])


### torch.tril(input, diagonal=0)
- input：输入张量，应该是一个至少有两维的矩阵。
- diagonal：一个可选的整数参数，用于指定主对角线的位置。默认值为0，表示主对角线。如果设置为正数，主对角线将向上移动；如果设置为负数，主对角线将向下移动。

In [4]:
import torch

# 创建一个二维张量（矩阵）
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# 使用tril生成下三角矩阵
tril_matrix = torch.tril(matrix)

# 打印原始矩阵和下三角矩阵
print("原始矩阵:\n", matrix)
print("下三角矩阵:\n", tril_matrix)


原始矩阵:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
下三角矩阵:
 tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])


### torch.ones_like(input)
- input：输入张量，新张量的形状将与此张量相同。

In [5]:
import torch

# 创建一个二维张量（矩阵）
original_tensor = torch.tensor([[1, 2, 3],
                                 [4, 5, 6]])

# 使用ones_like生成一个与原始张量形状相同的全1张量
ones_tensor = torch.ones_like(original_tensor)

# 打印原始张量和全1张量
print("原始张量:\n", original_tensor)
print("全1张量:\n", ones_tensor)


原始张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])
全1张量:
 tensor([[1, 1, 1],
        [1, 1, 1]])


### tensor.contiguous()
- 这个函数返回一个新的张量，其数据与原始张量相同，但内存是连续的。如果原始张量的内存已经是连续的，那么contiguous函数将返回原始张量本身。

In [7]:
import torch

# 创建一个三维张量
original_tensor = torch.randn(2, 3, 4)

# 对张量进行转置操作
transposed_tensor = original_tensor.transpose(1, 2)

# 尝试直接对转置后的张量进行view操作
# 这可能会失败，因为转置后的张量内存可能不是连续的
try:
    reshaped_tensor = transposed_tensor.view(2, 12)
except RuntimeError as e:
    print("错误:", e)

# 使用contiguous函数确保内存连续性，然后进行view操作
contiguous_tensor = transposed_tensor.contiguous()
reshaped_tensor = contiguous_tensor.view(2, 12)

print("转置后的张量形状:", transposed_tensor.shape)
print("重塑后的张量形状:", reshaped_tensor.shape)


错误: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
转置后的张量形状: torch.Size([2, 4, 3])
重塑后的张量形状: torch.Size([2, 12])
